repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-ll']

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.74.0
    hooks:
      - id: semgrep
        args: ['--config=auto']
