name: Python SAST
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SAST tools
        run: |
          pip install bandit semgrep

      - name: Run Bandit (Python SAST)
        run: |
          bandit -r . -ll -f json -o bandit-report.json || true

      - name: Run Semgrep (Pattern-Based SAST)
        run: |
          semgrep scan --config=auto --json > semgrep-report.json || true

      # ✅ Always upload reports, even if previous steps failed
      - name: Upload SAST reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            bandit-report.json
            semgrep-report.json
