name: Python SAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write   # needed for SARIF upload

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    continue-on-error: true   # ✅ still allows merging

    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4

      # --- Setup Python ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- Install open-source SAST tools ---
      - name: Install Bandit and Semgrep
        run: |
          pip install bandit semgrep

      # --- Run Bandit ---
      - name: Run Bandit (Python SAST)
        run: |
          # Run Bandit and save JSON output
          bandit -r . -ll -f json -o bandit-report.json || true

          # Convert JSON → SARIF if Bandit SARIF output not supported
          python3 - <<'EOF'
          import json, pathlib
          src = pathlib.Path("bandit-report.json")
          if src.exists() and src.stat().st_size > 0:
              data = json.load(src.open())
              sarif = {
                  "version": "2.1.0",
                  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
                  "runs": [{
                      "tool": {"driver": {"name": "Bandit"}},
                      "results": [{
                          "ruleId": i.get("test_id"),
                          "level": i.get("issue_severity", "note").lower(),
                          "message": {"text": i.get("issue_text")},
                          "locations": [{
                              "physicalLocation": {
                                  "artifactLocation": {"uri": i.get("filename")},
                                  "region": {"startLine": i.get("line_number", 1)}
                              }
                          }]
                      } for i in data.get("results", [])]
                  }]
              }
              pathlib.Path("bandit-report.sarif").write_text(json.dumps(sarif, indent=2))
          else:
              pathlib.Path("bandit-report.sarif").write_text('{"version":"2.1.0","runs":[]}')
          EOF

      # --- Run Semgrep ---
      - name: Run Semgrep (Pattern-Based SAST)
        run: |
          semgrep scan --config=auto --json > semgrep-report.json || true
          semgrep scan --config=auto --sarif-output semgrep-report.sarif || true

      # --- Show summary in logs ---
      - name: Show Bandit summary
        if: always()
        run: |
          python3 - <<'EOF'
          import json, pathlib
          f = pathlib.Path('bandit-report.json')
          if f.exists() and f.stat().st_size > 0:
              data = json.load(f.open())
              print("\n=== Bandit Findings Summary ===")
              for issue in data.get('results', []):
                  print(f"{issue['filename']}:{issue['line_number']} -> {issue['issue_severity']} - {issue['issue_text']}")
          else:
              print("No Bandit findings or report empty.")
          EOF

      # --- Upload all reports as artifacts ---
      - name: Upload SAST reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            bandit-report.json
            semgrep-report.json
            bandit-report.sarif
            semgrep-report.sarif

      # --- Upload SARIF to GitHub Security tab ---
      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            bandit-report.sarif
            semgrep-report.sarif
