name: Python SAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    continue-on-error: true   # ✅ still allows merging

    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4

      # --- Setup Python ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- Install open-source tools ---
      - name: Install Bandit and Semgrep
        run: |
          pip install bandit semgrep

      # --- Run Bandit ---
      - name: Run Bandit
        run: |
          bandit -r . -ll -f json -o bandit-report.json || true

      # --- Run Semgrep ---
      - name: Run Semgrep
        run: |
          semgrep scan --config=auto --json > semgrep-report.json || true

      # --- Show a summary of Bandit findings in logs ---
      - name: Show Bandit summary
        if: always()
        run: |
          python3 - <<'EOF'
          import json, pathlib
          f = pathlib.Path('bandit-report.json')
          if f.exists() and f.stat().st_size > 0:
              data = json.load(f.open())
              print("\n=== Bandit Findings Summary ===")
              for issue in data.get('results', []):
                  print(f"{issue['filename']}:{issue['line_number']} -> {issue['issue_severity']} - {issue['issue_text']}")
          else:
              print("No Bandit findings or report empty.")
          EOF

      # --- Upload reports as artifacts for download ---
      - name: Upload SAST reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            bandit-report.json
            semgrep-report.json
